### ISSUE TITLE
table-list hints on select elements missing from result or changed to default hint

### ISSUE THREAD

**Issue by MartijnR** [SEL-Columbia/pyxform#62] opened 2012-11-14 18:02 UTC
Hints on the first row, (the headings), are ignored for headings with text labels and overridden by a default message for headings with an image (2 different bugs).

See http://dev.formhub.org/martijnr/forms/table-list for XLS and XML documents (enketo: http://e3crc.enketo-dev.formhub.org/webform)

First table, hint on first row: 
- expected: "This is a user-defined hint for the 1st row"
- actual: null (there is no `<hint>` element in the result)

Second table, hint on first row:
- expected: "This is a user-defined hint for the 1st row"
- actual: 'Select all that apply'

**Comment by nathanathan** [comment] 2012-11-14 19:10
Groups have this problem in general if you try to add hints to them. Part of the issue is that a group can just be an abstract grouping of questions if it doesn't have an appearance tag on it, so it doesn't make sense for them to have labels or hints in that situation. The simplest fix would probably be to change xls2json.py so that table-lists generate an additional note-like element at the beginning of the group with the group's label/hint/media.
The 'Select all that apply' hint is coming from the `appearance="label"` select element which xls2json auto-generates for field-lists. It could be fixed by giving the auto-generated hint an empty string hint property to override the default.

**Comment by MartijnR** [comment] 2012-11-14 19:50
Thanks Nathan,

Not sure if this is related to groups (I believe that groups that have a label are 'visual' groups - and thus can have hints - and groups without a label are not). In this case it is just a matter of adding the `<hint>` element right after the empty label element of the `<select1>` (as done in the second table. For the second issue, the sample form did attempt to override but the override failed and the default was shown. So the code below is the one currently generated:

``` xml
    <group appearance="field-list" ref="/table-list/table_list_test2">
      <label>Table (made with an easier method)</label>
      <select1 appearance="label" ref="/table-list/table_list_test2/reserved_name_for_field_list_labels_4">
        <label> </label>
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
      <select1 appearance="list-nolabel" ref="/table-list/table_list_test2/table_list_3">
        <label>Q1</label>
        <hint>This is a user-defined hint for the 2nd row</hint>
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
      <select1 appearance="list-nolabel" ref="/table-list/table_list_test2/table_list_4">
        <label>Question 2</label>
        <hint>This is a user-defined hint for the 3rd row</hint>
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
    </group>
    <group appearance="field-list" ref="/table-list/happy_sad_table">
      <label>Table with image labels (made using an easier method)</label>
      <select appearance="label" ref="/table-list/happy_sad_table/reserved_name_for_field_list_labels_8">
        <label> </label>
        <hint>Select all that apply.</hint>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/reserved_name_for_field_list_labels_8/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/reserved_name_for_field_list_labels_8/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
      <select appearance="list-nolabel" ref="/table-list/happy_sad_table/happy_sad_brian">
        <label>Brian</label>
        <hint>This is a user-defined hint for the 2nd row</hint>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_brian/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_brian/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
      <select appearance="list-nolabel" ref="/table-list/happy_sad_table/happy_sad_michael">
        <label>Michael</label>
        <hint>This is a user-defined hint for the 3rd row</hint>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_michael/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_michael/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
    </group>
```

But I think this is what is desired (highlighted the changes with /************/):

``` xml
    <group appearance="field-list" ref="/table-list/table_list_test2">
      <label>Table (made with an easier method)</label>
      <select1 appearance="label" ref="/table-list/table_list_test2/reserved_name_for_field_list_labels_4">
        <label> </label>
        /*****************************************************************************************/
        <hint>This is a user-defined hint for the 1st row</hint>/******* missing node *******/
       /*****************************************************************************************/
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
      <select1 appearance="list-nolabel" ref="/table-list/table_list_test2/table_list_3">
        <label>Q1</label>
        <hint>This is a user-defined hint for the 2nd row</hint>
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
      <select1 appearance="list-nolabel" ref="/table-list/table_list_test2/table_list_4">
        <label>Question 2</label>
        <hint>This is a user-defined hint for the 3rd row</hint>
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
    </group>
    <group appearance="field-list" ref="/table-list/happy_sad_table">
      <label>Table with image labels (made using an easier method)</label>
      <select appearance="label" ref="/table-list/happy_sad_table/reserved_name_for_field_list_labels_8">
        <label> </label>
         /******************************************************************************************************/
        <hint>This is a user-defined hint for the 1st row</hint>/****** text according to XLS sheet *******/
         /*****************************************************************************************************/
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/reserved_name_for_field_list_labels_8/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/reserved_name_for_field_list_labels_8/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
      <select appearance="list-nolabel" ref="/table-list/happy_sad_table/happy_sad_brian">
        <label>Brian</label>
        <hint>This is a user-defined hint for the 2nd row</hint>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_brian/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_brian/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
      <select appearance="list-nolabel" ref="/table-list/happy_sad_table/happy_sad_michael">
        <label>Michael</label>
        <hint>This is a user-defined hint for the 3rd row</hint>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_michael/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_michael/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
    </group>
```

Sorry, if I'm misunderstanding your reply.

**Comment by nathanathan** [comment] 2012-11-15 18:24
That could work. However, I haven't seen hints used inside of group elements before and I wonder if there is a reason they were left out originally. There could be a display issue in collect. [In the Multi list group example here the group label is rendered differently from a question label.](http://opendatakit.org/help/form-design/examples/)

**Comment by MartijnR** [comment] 2012-11-15 19:17
Thanks @nathanathan,

I think the ODK page doesn't show hints because they're not in the xml/xls (but could have been) or maybe it has changed. I corrected the xml by hand (see https://jrosaforms.appspot.com/www/formXml?readable=true&formId=table-list) and loaded it in ODK collect. The current version of ODK Collect shows all the hints if they're in the XML. See this screenshot:http://imgur.com/o9Nwo.

**Comment by nathanathan** [comment] 2012-11-15 19:56
Opps, sorry I missed that in your XML the hint was inside the table-list's `<select appearance="label">` element.
That solves the problem for table-lists, but on a standard field-list without a `<select appearance="label">` element to put the hint in I think the hint will go missing. And what I'm not sure about is whether it works to put the `<hint>` element along side the `<label>` element directly inside the group. e.g.

```
    <group appearance="field-list" ref="/table-list/table_list_test2">
      <label>Table (made with an easier method)</label>
      <hint>This is a user-defined hint in the group's row.</hint>
      <select1 appearance="label" ref="/table-list/table_list_test2/reserved_name_for_field_list_labels_4">
        <label> </label>
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
      <select1 appearance="list-nolabel" ref="/table-list/table_list_test2/table_list_3">
        <label>Q1</label>
        <hint>This is a user-defined hint for the 2nd row</hint>
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
      <select1 appearance="list-nolabel" ref="/table-list/table_list_test2/table_list_4">
        <label>Question 2</label>
        <hint>This is a user-defined hint for the 3rd row</hint>
        <item>
          <label>Yes</label>
          <value>yes</value>
        </item>
        <item>
          <label>No</label>
          <value>no</value>
        </item>
      </select1>
    </group>
    <group appearance="field-list" ref="/table-list/happy_sad_table">
      <label>Table with image labels (made using an easier method)</label>
      <hint>This is a user-defined hint in the group's row.</hint>
      <select appearance="label" ref="/table-list/happy_sad_table/reserved_name_for_field_list_labels_8">
        <label> </label>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/reserved_name_for_field_list_labels_8/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/reserved_name_for_field_list_labels_8/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
      <select appearance="list-nolabel" ref="/table-list/happy_sad_table/happy_sad_brian">
        <label>Brian</label>
        <hint>This is a user-defined hint for the 2nd row</hint>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_brian/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_brian/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
      <select appearance="list-nolabel" ref="/table-list/happy_sad_table/happy_sad_michael">
        <label>Michael</label>
        <hint>This is a user-defined hint for the 3rd row</hint>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_michael/happy:label')"/>
          <value>happy</value>
        </item>
        <item>
          <label ref="jr:itext('/table-list/happy_sad_table/happy_sad_michael/sad:label')"/>
          <value>sad</value>
        </item>
      </select>
    </group>
```

**Comment by MartijnR** [comment] 2012-11-15 20:24
Right, these two issues described in the first post are not about hints on group labels. You got me interested in that too though..... I am going to check if that works in ODK collect (and will create a new issue if it does). Thanks,

**Comment by MartijnR** [comment] 2012-11-15 20:26
Edited the title of this issue to make clearer it's about select elements

**Closed as completed** 2013-03-21 08:17 UTC
Labels: bug
